# dein itself
[[plugins]]
repo	= 'Shougo/dein.vim'

# Color Scheme
[[plugins]]
#repo	= 'morhetz/gruvbox'
repo	= 'nielsmadan/harlequin'

# NERD Tree
[[plugins]]
repo	= 'scrooloose/nerdtree'

# DirDiff
[[plugins]]
repo	= 'will133/vim-dirdiff'

# SystemVerilog Syntax
[[plugins]]
repo	= 'nachumk/systemverilog.vim'

# Conque GDB
[[plugins]]
repo	= 'vim-scripts/Conque-GDB'

# Git-gutter
[[plugins]]
repo	= 'airblade/vim-gitgutter'

# YouCompleteMe
[[plugins]]
repo    = 'ycm-core/YouCompleteMe'
build   = 'python3 install.py --clang-completer'

# fzf
[[plugins]]
repo	= 'junegunn/fzf'
build   = './install --all'

[[plugins]]
repo	= 'junegunn/fzf.vim'

