# dein itself
[[plugins]]
repo	= 'Shougo/dein.vim'

# Color Scheme
[[plugins]]
#repo	= 'morhetz/gruvbox'
repo	= 'nielsmadan/harlequin'

# NERD Tree
[[plugins]]
repo	= 'scrooloose/nerdtree'

# DirDiff
[[plugins]]
repo	= 'will133/vim-dirdiff'

# SystemVerilog Syntax
[[plugins]]
repo	= 'nachumk/systemverilog.vim'

# Conque GDB
[[plugins]]
repo	= 'vim-scripts/Conque-GDB'

# Git-gutter
[[plugins]]
repo	= 'airblade/vim-gitgutter'

