# dein itself
[[plugins]]
repo	= 'Shougo/dein.vim'

# Color Scheme
[[plugins]]
repo	= 'morhetz/gruvbox'

# NERD Tree
[[plugins]]
repo	= 'scrooloose/nerdtree'

# DirDiff
[[plugins]]
repo	= 'will133/vim-dirdiff'

# SystemVerilog Syntax
[[plugins]]
repo	= 'nachumk/systemverilog.vim'

# git-gutter
[[plugins]]
repo	= 'airblade/vim-gitgutter'

