# dein itself
[[plugins]]
repo	= 'Shougo/dein.vim'

# Color Scheme
[[plugins]]
#repo	= 'morhetz/gruvbox'
repo	= 'nielsmadan/harlequin'

# NERD Tree
[[plugins]]
repo	= 'scrooloose/nerdtree'

# DirDiff
[[plugins]]
repo	= 'will133/vim-dirdiff'

