# Plugins for neovim
[[plugins]]
repo	= 'neovim/nvim-lspconfig'

[[plugins]]
repo	= 'hrsh7th/nvim-cmp'

[[plugins]]
repo	= 'hrsh7th/cmp-nvim-lsp'

[[plugins]]
repo	= 'hrsh7th/cmp-buffer'

[[plugins]]
repo	= 'hrsh7th/cmp-vsnip'

[[plugins]]
repo	= 'hrsh7th/vim-vsnip'

[[plugins]]
repo	= 'windwp/nvim-autopairs'

